version: "1"
services:
    www:
        build: .
        ports: 
            - "3001:80"
        volumes:
            - ./www:/var/www/html/
            - ./src:/var/www/src/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3020:3306"
        environment:
            MYSQL_DATABASE: master
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
